/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelCarrinhosRouteImport } from './routes/painel.carrinhos'
import { Route as PainelDiagnosticoRouteImport } from './routes/painel.diagnostico'
import { Route as PainelEnviosRouteImport } from './routes/painel.envios'
import { Route as PainelOtimizacaoRouteImport } from './routes/painel.otimizacao'
import { Route as PainelReguaRouteImport } from './routes/painel.regua'
import { Route as PainelRelatorioRouteImport } from './routes/painel.relatorio'
import { Route as PainelSegurancaRouteImport } from './routes/painel.seguranca'
import { Route as PainelShopifyRouteImport } from './routes/painel.shopify'
import { Route as PainelTemplatesRouteImport } from './routes/painel.templates'
import { Route as PainelTestesAbRouteImport } from './routes/painel.testes-ab'
import { Route as PainelVariacoesRouteImport } from './routes/painel.variacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCarrinhosRoute = PainelCarrinhosRouteImport.update({
  id: '/carrinhos',
  path: '/carrinhos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDiagnosticoRoute = PainelDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEnviosRoute = PainelEnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => PainelRoute,
} as any)
const PainelOtimizacaoRoute = PainelOtimizacaoRouteImport.update({
  id: '/otimizacao',
  path: '/otimizacao',
  getParentRoute: () => PainelRoute,
} as any)
const PainelReguaRoute = PainelReguaRouteImport.update({
  id: '/regua',
  path: '/regua',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRelatorioRoute = PainelRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSegurancaRoute = PainelSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => PainelRoute,
} as any)
const PainelShopifyRoute = PainelShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => PainelRoute,
} as any)
const PainelTemplatesRoute = PainelTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => PainelRoute,
} as any)
const PainelTestesAbRoute = PainelTestesAbRouteImport.update({
  id: '/testes-ab',
  path: '/testes-ab',
  getParentRoute: () => PainelRoute,
} as any)
const PainelVariacoesRoute = PainelVariacoesRouteImport.update({
  id: '/variacoes',
  path: '/variacoes',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/carrinhos': typeof PainelCarrinhosRoute
  '/painel/diagnostico': typeof PainelDiagnosticoRoute
  '/painel/envios': typeof PainelEnviosRoute
  '/painel/otimizacao': typeof PainelOtimizacaoRoute
  '/painel/regua': typeof PainelReguaRoute
  '/painel/relatorio': typeof PainelRelatorioRoute
  '/painel/seguranca': typeof PainelSegurancaRoute
  '/painel/shopify': typeof PainelShopifyRoute
  '/painel/templates': typeof PainelTemplatesRoute
  '/painel/testes-ab': typeof PainelTestesAbRoute
  '/painel/variacoes': typeof PainelVariacoesRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/carrinhos': typeof PainelCarrinhosRoute
  '/painel/diagnostico': typeof PainelDiagnosticoRoute
  '/painel/envios': typeof PainelEnviosRoute
  '/painel/otimizacao': typeof PainelOtimizacaoRoute
  '/painel/regua': typeof PainelReguaRoute
  '/painel/relatorio': typeof PainelRelatorioRoute
  '/painel/seguranca': typeof PainelSegurancaRoute
  '/painel/shopify': typeof PainelShopifyRoute
  '/painel/templates': typeof PainelTemplatesRoute
  '/painel/testes-ab': typeof PainelTestesAbRoute
  '/painel/variacoes': typeof PainelVariacoesRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/carrinhos': typeof PainelCarrinhosRoute
  '/painel/diagnostico': typeof PainelDiagnosticoRoute
  '/painel/envios': typeof PainelEnviosRoute
  '/painel/otimizacao': typeof PainelOtimizacaoRoute
  '/painel/regua': typeof PainelReguaRoute
  '/painel/relatorio': typeof PainelRelatorioRoute
  '/painel/seguranca': typeof PainelSegurancaRoute
  '/painel/shopify': typeof PainelShopifyRoute
  '/painel/templates': typeof PainelTemplatesRoute
  '/painel/testes-ab': typeof PainelTestesAbRoute
  '/painel/variacoes': typeof PainelVariacoesRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/painel/carrinhos'
    | '/painel/diagnostico'
    | '/painel/envios'
    | '/painel/otimizacao'
    | '/painel/regua'
    | '/painel/relatorio'
    | '/painel/seguranca'
    | '/painel/shopify'
    | '/painel/templates'
    | '/painel/testes-ab'
    | '/painel/variacoes'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel/carrinhos'
    | '/painel/diagnostico'
    | '/painel/envios'
    | '/painel/otimizacao'
    | '/painel/regua'
    | '/painel/relatorio'
    | '/painel/seguranca'
    | '/painel/shopify'
    | '/painel/templates'
    | '/painel/testes-ab'
    | '/painel/variacoes'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/painel/carrinhos'
    | '/painel/diagnostico'
    | '/painel/envios'
    | '/painel/otimizacao'
    | '/painel/regua'
    | '/painel/relatorio'
    | '/painel/seguranca'
    | '/painel/shopify'
    | '/painel/templates'
    | '/painel/testes-ab'
    | '/painel/variacoes'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/carrinhos': {
      id: '/painel/carrinhos'
      path: '/carrinhos'
      fullPath: '/painel/carrinhos'
      preLoaderRoute: typeof PainelCarrinhosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/diagnostico': {
      id: '/painel/diagnostico'
      path: '/diagnostico'
      fullPath: '/painel/diagnostico'
      preLoaderRoute: typeof PainelDiagnosticoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/envios': {
      id: '/painel/envios'
      path: '/envios'
      fullPath: '/painel/envios'
      preLoaderRoute: typeof PainelEnviosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/otimizacao': {
      id: '/painel/otimizacao'
      path: '/otimizacao'
      fullPath: '/painel/otimizacao'
      preLoaderRoute: typeof PainelOtimizacaoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/regua': {
      id: '/painel/regua'
      path: '/regua'
      fullPath: '/painel/regua'
      preLoaderRoute: typeof PainelReguaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/relatorio': {
      id: '/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof PainelRelatorioRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/seguranca': {
      id: '/painel/seguranca'
      path: '/seguranca'
      fullPath: '/painel/seguranca'
      preLoaderRoute: typeof PainelSegurancaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/shopify': {
      id: '/painel/shopify'
      path: '/shopify'
      fullPath: '/painel/shopify'
      preLoaderRoute: typeof PainelShopifyRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/templates': {
      id: '/painel/templates'
      path: '/templates'
      fullPath: '/painel/templates'
      preLoaderRoute: typeof PainelTemplatesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/testes-ab': {
      id: '/painel/testes-ab'
      path: '/testes-ab'
      fullPath: '/painel/testes-ab'
      preLoaderRoute: typeof PainelTestesAbRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/variacoes': {
      id: '/painel/variacoes'
      path: '/variacoes'
      fullPath: '/painel/variacoes'
      preLoaderRoute: typeof PainelVariacoesRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelCarrinhosRoute: typeof PainelCarrinhosRoute
  PainelDiagnosticoRoute: typeof PainelDiagnosticoRoute
  PainelEnviosRoute: typeof PainelEnviosRoute
  PainelOtimizacaoRoute: typeof PainelOtimizacaoRoute
  PainelReguaRoute: typeof PainelReguaRoute
  PainelRelatorioRoute: typeof PainelRelatorioRoute
  PainelSegurancaRoute: typeof PainelSegurancaRoute
  PainelShopifyRoute: typeof PainelShopifyRoute
  PainelTemplatesRoute: typeof PainelTemplatesRoute
  PainelTestesAbRoute: typeof PainelTestesAbRoute
  PainelVariacoesRoute: typeof PainelVariacoesRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelCarrinhosRoute: PainelCarrinhosRoute,
  PainelDiagnosticoRoute: PainelDiagnosticoRoute,
  PainelEnviosRoute: PainelEnviosRoute,
  PainelOtimizacaoRoute: PainelOtimizacaoRoute,
  PainelReguaRoute: PainelReguaRoute,
  PainelRelatorioRoute: PainelRelatorioRoute,
  PainelSegurancaRoute: PainelSegurancaRoute,
  PainelShopifyRoute: PainelShopifyRoute,
  PainelTemplatesRoute: PainelTemplatesRoute,
  PainelTestesAbRoute: PainelTestesAbRoute,
  PainelVariacoesRoute: PainelVariacoesRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
